<<<<<<< HEAD
version: '3.8'

services:
  db:
    image: postgres:15-alpine
    container_name: postgres_db
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: student_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
=======
version: "3.9"

services:
  app:
    image: nginx:latest
    ports:
      - "80:80"
>>>>>>> f31980649d93632b2012a8756d7ae861ed48175c
