name: Postman API Tests

on:
  push:
    branches:
      - main
      - development
      - release
      - production

  pull_request:
    branches:
      - main
      - production

jobs:
  api-test:
    name: Postman API Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install Newman
        run: npm install -g newman

      - name: Run Postman Tests
        run: newman run collection.json